site_name: Documentations for example functions
theme:
  name: material
nav:
  - Home: index.md
  - Tutorials:
    - my_adder_tutorial.md
    - my_thermo_stat_tutorial.md
    - have_digits_tutorial.md
    - area_of_rectangle_tutorial.md
    - perimeter_of_rectangle_tutorial.md
  - How-to-guides:
    - my_adder_how_to_guide.md
    - my_thermo_stat_how_to_guide.md
    - have_digits_how_to_guide.md
    - area_of_rectangle_how_to_guide.md
    - perimeter_of_rectangle_how_to_guide.md
  - References:
    - my_adder_ref.md
    - my_thermo_stat_ref.md
    - have_digits_ref.md
    - area_of_rectangle_ref.md
    - perimeter_of_rectangle_ref.md
  - Explanations:
    - my_adder_explanation.md
    - my_thermo_stat_explanation.md
    - have_digits_explanation.md
    - area_of_rectangle_explanation.md
    - perimeter_of_rectangle_explanation.md